window.env = {
  "TERM_PROGRAM": "vscode",
  "NODE": "/usr/local/bin/node",
  "INIT_CWD": "/Users/vitaliypyak/Desktop/booklist_test",
  "TERM": "xterm-256color",
  "SHELL": "/bin/zsh",
  "npm_config_metrics_registry": "https://registry.npmjs.org/",
  "TMPDIR": "/var/folders/nz/l1fx0nh532n12qbn1kp0k56w0000gn/T/",
  "npm_config_global_prefix": "/usr/local",
  "TERM_PROGRAM_VERSION": "1.82.0",
  "ZDOTDIR": "/Users/vitaliypyak",
  "ORIGINAL_XDG_CURRENT_DESKTOP": "undefined",
  "MallocNanoZone": "0",
  "COLOR": "1",
  "npm_config_noproxy": "",
  "npm_config_local_prefix": "/Users/vitaliypyak/Desktop/booklist_test",
  "USER": "vitaliypyak",
  "COMMAND_MODE": "unix2003",
  "npm_config_globalconfig": "/usr/local/etc/npmrc",
  "SSH_AUTH_SOCK": "/private/tmp/com.apple.launchd.K7O3zomuA8/Listeners",
  "__CF_USER_TEXT_ENCODING": "0x1F5:0x7:0x31",
  "npm_execpath": "/usr/local/lib/node_modules/npm/bin/npm-cli.js",
  "PATH": "/Users/vitaliypyak/Desktop/booklist_test/node_modules/.bin:/Users/vitaliypyak/Desktop/node_modules/.bin:/Users/vitaliypyak/node_modules/.bin:/Users/node_modules/.bin:/node_modules/.bin:/usr/local/lib/node_modules/npm/node_modules/@npmcli/run-script/lib/node-gyp-bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin",
  "npm_package_json": "/Users/vitaliypyak/Desktop/booklist_test/package.json",
  "_": "/Users/vitaliypyak/Desktop/booklist_test/node_modules/.bin/react-dotenv",
  "npm_config_userconfig": "/Users/vitaliypyak/.npmrc",
  "npm_config_init_module": "/Users/vitaliypyak/.npm-init.js",
  "USER_ZDOTDIR": "/Users/vitaliypyak",
  "__CFBundleIdentifier": "com.microsoft.VSCode",
  "npm_command": "run-script",
  "PWD": "/Users/vitaliypyak/Desktop/booklist_test",
  "npm_lifecycle_event": "build",
  "EDITOR": "vi",
  "npm_package_name": "booklist",
  "LANG": "en_US.UTF-8",
  "VSCODE_GIT_ASKPASS_EXTRA_ARGS": "--ms-enable-electron-run-as-node",
  "XPC_FLAGS": "0x0",
  "npm_config_node_gyp": "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js",
  "npm_package_version": "0.1.0",
  "XPC_SERVICE_NAME": "0",
  "VSCODE_INJECTION": "1",
  "SHLVL": "2",
  "HOME": "/Users/vitaliypyak",
  "VSCODE_GIT_ASKPASS_MAIN": "/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass-main.js",
  "npm_config_cache": "/Users/vitaliypyak/.npm",
  "LOGNAME": "vitaliypyak",
  "npm_lifecycle_script": "react-dotenv && react-scripts build",
  "VSCODE_GIT_IPC_HANDLE": "/var/folders/nz/l1fx0nh532n12qbn1kp0k56w0000gn/T/vscode-git-84bba2197f.sock",
  "npm_config_user_agent": "npm/9.5.1 node/v18.16.0 darwin x64 workspaces/false",
  "VSCODE_GIT_ASKPASS_NODE": "/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin)",
  "GIT_ASKPASS": "/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass.sh",
  "npm_node_execpath": "/usr/local/bin/node",
  "npm_config_prefix": "/usr/local",
  "COLORTERM": "truecolor",
  "REACT_APP_API_KEY": "AIzaSyAr_hDaif-AnB-EhuYN_mYm-Y-kgR0PNZg"
};